### ISSUE TITLE
Flip order in association?

### ISSUE THREAD

**Issue by g-bauer** [cphyc/fortran-syntax#1]
I think there is a small mistake in the README. The association statements for precision have to be swapped, i.e. `dp=>real64`  instead of `real64=>dp`

**Comment by cphyc** [comment]
Hi!
It's a matter of convention anyway, the point of the rule was more to warn people about using `real(8)` than being pedantic about whether to use `dp` vs. `real64`. Is there somewhere a discussion about which one should be preferred over which?

**Comment by cphyc** [comment]
In any case, I updated the Readme to reflect your comment.

**Comment by g-bauer** [comment]
Hey,

I think `real64=>dp` won't work since `real64` is the parameter you are pulling from `iso_fortran_env`.
